from datetime import date
from decimal import Decimal


DEMO_CUSTOMERS = [
    {
        "first_name": "Sarah",
        "last_name": "Miller",
        "email": "sarah.miller@example.com",
        "phone": "+1-415-555-0101",
        "email_opt_in": True,
        "sms_opt_in": True,
        "unsubscribed": False,
        "lifetime_value": Decimal("780.00"),
        "engagement_score": Decimal("92.00"),
        "purchases": [
            {
                "product_name": "Wireless Earbuds",
                "product_category": "Audio",
                "product_description": "Compact wireless earbuds with clear calls and long battery life.",
                "amount": Decimal("129.99"),
                "purchase_date": date(2026, 6, 10),
            },
            {
                "product_name": "Bluetooth Speaker",
                "product_category": "Audio",
                "product_description": "Portable waterproof speaker with rich bass for travel and home use.",
                "amount": Decimal("89.99"),
                "purchase_date": date(2026, 5, 5),
            },
        ],
    },
    {
        "first_name": "Rahul",
        "last_name": "Sharma",
        "email": "rahul.sharma@example.com",
        "phone": "+1-212-555-0134",
        "email_opt_in": True,
        "sms_opt_in": False,
        "unsubscribed": False,
        "lifetime_value": Decimal("260.00"),
        "engagement_score": Decimal("58.00"),
        "purchases": [
            {
                "product_name": "MagSafe Phone Case",
                "product_category": "Phone Accessories",
                "product_description": "Slim protective phone case with magnetic charging support.",
                "amount": Decimal("39.99"),
                "purchase_date": date(2026, 4, 20),
            },
            {
                "product_name": "USB-C Fast Charger",
                "product_category": "Phone Accessories",
                "product_description": "Compact wall charger with fast USB-C power delivery.",
                "amount": Decimal("29.99"),
                "purchase_date": date(2026, 3, 18),
            },
        ],
    },
    {
        "first_name": "Maya",
        "last_name": "Patel",
        "email": "maya.patel@example.com",
        "phone": "+1-646-555-0177",
        "email_opt_in": True,
        "sms_opt_in": False,
        "unsubscribed": False,
        "lifetime_value": Decimal("1380.00"),
        "engagement_score": Decimal("73.00"),
        "purchases": [
            {
                "product_name": "UltraBook Pro 14",
                "product_category": "Computers",
                "product_description": "Lightweight laptop for remote work, design, and productivity.",
                "amount": Decimal("1199.00"),
                "purchase_date": date(2026, 2, 12),
            },
            {
                "product_name": "Ergonomic Laptop Stand",
                "product_category": "Productivity Accessories",
                "product_description": "Adjustable aluminum stand for better laptop posture and cooling.",
                "amount": Decimal("79.99"),
                "purchase_date": date(2026, 3, 9),
            },
            {
                "product_name": "Wireless Keyboard",
                "product_category": "Productivity Accessories",
                "product_description": "Quiet low-profile keyboard for daily productivity workflows.",
                "amount": Decimal("99.99"),
                "purchase_date": date(2026, 4, 2),
            },
        ],
    },
    {
        "first_name": "David",
        "last_name": "Chen",
        "email": "david.chen@example.com",
        "phone": "+1-408-555-0199",
        "email_opt_in": False,
        "sms_opt_in": True,
        "unsubscribed": False,
        "lifetime_value": Decimal("1240.00"),
        "engagement_score": Decimal("88.00"),
        "purchases": [
            {
                "product_name": "Studio Wireless Headphones",
                "product_category": "Audio",
                "product_description": "Over-ear wireless headphones with premium sound and plush ear pads.",
                "amount": Decimal("249.99"),
                "purchase_date": date(2026, 5, 2),
            },
            {
                "product_name": "Smartwatch Elite",
                "product_category": "Wearables",
                "product_description": "Fitness and productivity smartwatch with advanced health tracking.",
                "amount": Decimal("399.99"),
                "purchase_date": date(2026, 1, 16),
            },
        ],
    },
    {
        "first_name": "Emily",
        "last_name": "Johnson",
        "email": "emily.johnson@example.com",
        "phone": "+1-303-555-0118",
        "email_opt_in": True,
        "sms_opt_in": True,
        "unsubscribed": True,
        "lifetime_value": Decimal("540.00"),
        "engagement_score": Decimal("41.00"),
        "purchases": [
            {
                "product_name": "Fitness Tracker",
                "product_category": "Wearables",
                "product_description": "Everyday fitness tracker with sleep insights and workout tracking.",
                "amount": Decimal("149.99"),
                "purchase_date": date(2026, 4, 28),
            },
            {
                "product_name": "Sport Earbuds",
                "product_category": "Audio",
                "product_description": "Sweat-resistant earbuds built for exercise and commuting.",
                "amount": Decimal("99.99"),
                "purchase_date": date(2026, 2, 22),
            },
        ],
    },
]
